"""
Django settings for meadery project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import environ
from django.contrib.messages import constants as messages
from pint import UnitRegistry

env = environ.Env(
    DEBUG=(bool, False)
)

MESSAGE_TAGS = {
        messages.DEBUG: 'alert-secondary',
        messages.INFO: 'alert-info',
        messages.SUCCESS: 'alert-success',
        messages.WARNING: 'alert-warning',
        messages.ERROR: 'alert-danger',
 }
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Load env files, if exists
environ.Env.read_env(os.path.join(BASE_DIR, '.env'), overwrite=True)  # new, this needs to be after the BASE_DIR variable

# Development defaults below; the Docker image (docker/app) overrides them with
# environment variables. See https://docs.djangoproject.com/en/stable/howto/deployment/checklist/


def _env_list(name: str, default: list[str]) -> list[str]:
    """Comma-separated environment variable -> list; the default when unset."""
    value = os.getenv(name)
    return [item.strip() for item in value.split(',') if item.strip()] if value else default


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS', ['192.168.1.35', '0.0.0.0', '127.0.0.1'])
# Needed when the site is reached through a different scheme/host than Django sees, e.g. https://cellar.example.com
CSRF_TRUSTED_ORIGINS = _env_list('DJANGO_CSRF_TRUSTED_ORIGINS', [])


# Application definition

INSTALLED_APPS = [
    'crispy_forms',
    "crispy_bootstrap4",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'apps.user',
    'apps.batchthis',
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Every view needs a logged-in user unless marked @login_not_required (the auth
    # login/logout/password-reset views already are). Sends others to LOGIN_URL.
    'django.contrib.auth.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'meadery.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.batchthis.context_processors.nav_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'meadery.wsgi.application'

# Logging

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
                'level': 'INFO',
            },
            'batchthis_file': {
                'class': 'logging.FileHandler',
                'level': 'DEBUG',
                'filename': './log/batchthis/debug.log',
                'formatter': 'verbose',
            },
        },
        'formatters': {
            'verbose': {
                'format': '{asctime} {name}.{funcName} {levelname} {message}',
                'style': '{',
            },
        },
        'loggers': {
            'django': {
                'handlers': ['console'],
                'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
                'propagate': False,
            },
            'apps.batchthis': {
                'handlers': ['batchthis_file'],
                'level': 'DEBUG',
                'propogate': False,
                'formatter': 'verbose',
            },
            'apps.batchthis.fields': {
                'handlers': ['batchthis_file'],
                'level': 'DEBUG',
                'propogate': False,
                'formatter': 'verbose',
            },
      },
}

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

# PostgreSQL when POSTGRES_HOST is set (the Docker setup - docker/postgres), else the local SQLite file.
if os.getenv('POSTGRES_HOST'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'HOST': os.environ['POSTGRES_HOST'],
            'PORT': os.getenv('POSTGRES_PORT', '5432'),
            'NAME': os.getenv('POSTGRES_DB', 'batchthis'),
            'USER': os.getenv('POSTGRES_USER', 'batchthis'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', ''),
            'CONN_MAX_AGE': 60,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
# `collectstatic` gathers every app's static files here for nginx to serve (DEBUG off).
STATIC_ROOT = os.getenv('DJANGO_STATIC_ROOT', os.path.join(BASE_DIR, 'staticfiles'))
CRISPY_TEMPLATE_PACK = 'bootstrap4'
LOGIN_URL = "login"   # /user/login/ (django.contrib.auth.urls); the default /accounts/login/ doesn't exist
LOGIN_REDIRECT_URL = "/batchthis"
LOGOUT_REDIRECT_URL = "/user/login/"
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR,'media')
DJANGO_PINT_UNIT_REGISTER = UnitRegistry(autoconvert_offset_to_baseunit=True) #autoconvert needed for degC and degF string parsing
DJANGO_PINT_UNIT_REGISTER.define('SpecificGravity = [Sucrose] = sg')
DJANGO_PINT_UNIT_REGISTER.define('Brix = [Sucrose] = bx')
DJANGO_PINT_UNIT_REGISTER.define('Plato = [Sucrose]')
#DJANGO_PINT_UNIT_REGISTER.define('Brix = (((182.4601 * sg - 775.6821) * sg + 1262.7794) * sg - 669.5622) = bx')