# Generated by Django 4.0 on 2022-08-10 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0003_activitylog_adjuncttype_fermentable_recipeadjuncts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FermentableType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='fermentable',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batchthis.fermentabletype'),
        ),
    ]
