# Generated by Django 3.0.3 on 2020-02-29 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('startdate', models.DateTimeField(auto_now=True)),
                ('enddate', models.DateTimeField(blank=True, null=True)),
                ('size', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'batches',
            },
        ),
        migrations.CreateModel(
            name='BatchNoteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BatchTestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text="Enter the unit identifier, i.e. 'mgL' or 'ph'", max_length=10)),
                ('label', models.CharField(help_text="Enter abbreviation label of the measured unit, i.e. 'mg/L'", max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fermenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('max_size', models.IntegerField()),
                ('used_size', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='Clean/Ready', max_length=15)),
                ('max_size_units', models.ForeignKey(on_delete=models.SET('_del'), related_name='fermenter_max_size_units', to='batchthis.Unit')),
                ('used_size_units', models.ForeignKey(blank=True, null=True, on_delete=models.SET('_del'), related_name='fermenter_used_size_units', to='batchthis.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='BatchTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('value', models.IntegerField()),
                ('description', models.CharField(max_length=250)),
                ('batch', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='batchthis.Batch')),
                ('type', models.ForeignKey(on_delete=models.SET('_del'), to='batchthis.BatchTestType')),
                ('units', models.ForeignKey(on_delete=models.SET('_del'), to='batchthis.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='BatchNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=models.SET('_del'), to='batchthis.BatchNoteType')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='fermenter',
            field=models.ManyToManyField(blank=True, related_name='batch', to='batchthis.Fermenter'),
        ),
        migrations.AddField(
            model_name='batch',
            name='size_units',
            field=models.ForeignKey(on_delete=models.SET('_del'), to='batchthis.Unit'),
        ),
    ]
