# Generated by Django 3.0.3 on 2020-02-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0002_auto_20200229_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchtest',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='batchtest',
            name='value',
            field=models.FloatField(),
        ),
    ]
