# Generated by Django 3.0.3 on 2020-02-29 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0003_auto_20200229_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchnote',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='batchthis.Batch'),
        ),
        migrations.AlterField(
            model_name='batchtest',
            name='batch',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='batchthis.Batch'),
        ),
    ]
