# Generated by Django 3.0.3 on 2021-05-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0004_auto_20200331_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('version', models.IntegerField()),
                ('type', models.CharField(max_length=30)),
                ('brewer', models.CharField(max_length=30)),
                ('batchSize', models.FloatField()),
                ('source', models.CharField(max_length=50)),
                ('pairing', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeFermentable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('version', models.IntegerField()),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='batchnote',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='batch',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('_del'), to='batchthis.Recipe'),
        ),
    ]
