# Generated by Django 4.0 on 2022-08-10 03:29

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0002_default_load'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AdjunctType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Fermentable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('version', models.IntegerField(null=True)),
                ('type', models.CharField(choices=[('juice', 'Juice'), ('fruit', 'Fruit'), ('honey', 'Honey'), ('grain', 'Grain'), ('extract', 'Extract'), ('sugar', 'Sugar')], max_length=30)),
                ('sugar_content', models.FloatField()),
                ('potential', models.FloatField()),
                ('supplier', models.CharField(max_length=75, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('color', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecipeAdjuncts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_metric', models.FloatField(default=0)),
                ('time_to_add', models.IntegerField()),
                ('amount_is_weight', models.BooleanField()),
                ('recipe_notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RecipeYeasts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('recipe_notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Yeasts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('version', models.IntegerField(null=True)),
                ('type', models.CharField(max_length=20)),
                ('form', models.CharField(choices=[('dry', 'Dry'), ('liquid', 'Liquid')], max_length=20)),
                ('min_temp', models.FloatField()),
                ('max_temp', models.FloatField()),
                ('flocculation', models.IntegerField()),
                ('attenuation', models.IntegerField()),
                ('notes', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='fermenter',
            name='max_size',
        ),
        migrations.RemoveField(
            model_name='fermenter',
            name='max_size_units',
        ),
        migrations.RemoveField(
            model_name='fermenter',
            name='name',
        ),
        migrations.RemoveField(
            model_name='fermenter',
            name='status',
        ),
        migrations.RemoveField(
            model_name='fermenter',
            name='used_size',
        ),
        migrations.RemoveField(
            model_name='fermenter',
            name='used_size_units',
        ),
        migrations.AddField(
            model_name='batch',
            name='lotId',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='fermenter',
            name='last_passivation',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='batchnote',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='batchtest',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('max_size', models.IntegerField()),
                ('used_size', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='Clean/Ready', max_length=15)),
                ('intended_use', models.CharField(max_length=30)),
                ('max_size_units', models.ForeignKey(on_delete=models.SET('_del'), related_name='fermenter_max_size_units', to='batchthis.unit')),
                ('used_size_units', models.ForeignKey(blank=True, null=True, on_delete=models.SET('_del'), related_name='fermenter_used_size_units', to='batchthis.unit')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeFermentable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_metric', models.FloatField(default=0)),
                ('notes', models.CharField(max_length=200)),
                ('is_fermentable', models.BooleanField()),
                ('intended_use', models.CharField(choices=[('PRI', 'Primary Fermentation'), ('SEC', 'Secondary Fermentation'), ('TER', 'Tertiary Fermentation'), ('RAC', 'Racking'), ('AGE', ' Long-term Aging')], default='PRI', max_length=3)),
                ('fermentable', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='batchthis.fermentable')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bs_file', models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='media/recipes'), upload_to='')),
                ('name', models.CharField(max_length=75)),
                ('dateCreated', models.DateField()),
                ('dateUpdated', models.DateField()),
                ('version', models.IntegerField()),
                ('type', models.CharField(max_length=30)),
                ('brewer', models.CharField(max_length=30)),
                ('batchSize', models.FloatField()),
                ('source', models.CharField(max_length=50, null=True)),
                ('pairing', models.CharField(max_length=250)),
                ('notes', models.TextField()),
                ('estOG', models.FloatField()),
                ('estFG', models.FloatField()),
                ('estABV', models.FloatField()),
                ('adjuncts', models.ManyToManyField(to='batchthis.RecipeAdjuncts')),
                ('fermentables', models.ManyToManyField(to='batchthis.RecipeFermentable')),
            ],
        ),
        migrations.CreateModel(
            name='Barrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=20)),
                ('toastLevel', models.CharField(max_length=25)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batchthis.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='AgingTank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batchthis.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='Adjuncts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('version', models.IntegerField(null=True)),
                ('use', models.CharField(choices=[('WTR', 'Water Agent'), ('BTL', 'Bottling'), ('PRI', 'Primary'), ('SEC', 'Secondary'), ('TER', 'Tertiary/Aging'), ('BOI', 'Boil'), ('TIN', 'Tincture'), ('RAC', 'Racking')], default='PRI', max_length=5)),
                ('use_for', models.CharField(max_length=50, null=True)),
                ('notes', models.CharField(max_length=200, null=True)),
                ('batch_size', models.IntegerField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batchthis.adjuncttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='activity',
            field=models.ManyToManyField(blank=True, related_name='batch', to='batchthis.ActivityLog'),
        ),
        migrations.AddField(
            model_name='batch',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('_del'), to='batchthis.recipe'),
        ),
        migrations.AddField(
            model_name='fermenter',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batchthis.vessel'),
            preserve_default=False,
        ),
    ]
