# Generated by Django 4.0 on 2022-08-10 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0004_fermentabletype_alter_fermentable_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='yeasts',
            field=models.ManyToManyField(to='batchthis.RecipeYeasts'),
        ),
        migrations.AddField(
            model_name='recipeadjuncts',
            name='adjunct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batchthis.adjuncts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeyeasts',
            name='yeast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batchthis.yeasts'),
            preserve_default=False,
        ),
    ]
