from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('batches', views.batchListing, name='batchListing'),
    path('addBatch', views.addBatch, name='addBatch'),
    path('addRecipe', views.addRecipe, name='addRecipe'),
    path('addRecipe/<int:pk>', views.addRecipe, name='editRecipe'),
    path('batch/<int:pk>', views.batch, name='batch'),
    path('batch/<int:pk>/edit', views.editBatch, name="editBatch"),
    path('recipe/<int:pk>', views.addRecipe), #TODO create views.recipe and update view
    path('recipe/<int:pk>/view', views.recipe, name="recipe"),
    path('recipe/<int:pk>/edit', views.addRecipe, name="editRecipe"),
    #path('recipe/<int:pk>/editFermentables', views.editFermentables),
    #path('recipe/<int:pk>/editFermentables', views.editModelFermentables),
    path('recipe/<int:pk>/editFermentables', views.editFermentables, name="editFermentables"),
    path('recipe/<int:pk>/editAdjuncts', views.editAdjuncts, name='editAdjuncts'),
    path('recipe/<int:pk>/editYeasts', views.editYeasts, name='editYeasts'),
    path('recipes', views.recipeListing, name="recipeListing"),
    path('batch/<int:pk>/addTest', views.batchTest, name='addDetailTest'),
    path('batch/<int:pk>/addNote', views.batchNote, name='addDetailNote'),
    path('batch/<int:pk>/addNote/<str:noteType>', views.batchNote, name='addDetailNoteType'),
    path('batch/<int:pk>/addStage', views.batchStage, name='addDetailStage'),
    path('batch/<int:pk>/transfer', views.batchTransfer, name='transferBatch'),
    path('batch/<int:pk>/addAddon', views.batchAddition, name="addDetailAddon"),
    path('batch/<int:pk>/batchGraphs', views.batchGraphs, name='batchGraphs'),
    path('batch/<int:pk>/activity', views.activity, name="batchActivity"),
    path('vessels', views.vesselListing, name='vesselListing'),
    path('vessels/add', views.vesselCreate, name='addVessel'),
    path('vessel/<int:pk>', views.vessel, name='vessel'),
    path('vessel/<int:pk>/edit', views.vesselEdit, name='editVessel'),
    path('vessel/<int:pk>/clean', views.markVesselCleaned, name='markVesselCleaned'),
    path('vessel/<int:pk>/out-of-service', views.takeVesselOutOfService, name='takeVesselOutOfService'),
    path('vessel/<int:pk>/return-to-service', views.returnVesselToService, name='returnVesselToService'),
    path('utils/refractometerCorrection', views.refractometerCorrection, name="refractometerCorrection"),
    path('rpc/categoryFilterByStyle', views.categoryFilterByStyle, name="categoryFilterByStyle"),
    path('rpc/getDataFromRecipe', views.getDataFromRecipe, name="getDataFromRecipe"),
    path('rpc/utils/<str:action>/', views.utilities, name="utils"),
    path('admin/import', views.admin_import, name="admin_import"),
    path('api/fermentables/', views.FermentableListAPIView.as_view(), name="fermentable-list"),
    path('api/adjuncts/', views.AdjunctListAPIView.as_view(), name="adjunct-list"),
    path('api/yeasts/', views.YeastListAPIView.as_view(), name="yeast-list"),
    path('api/recipes/', views.RecipeListAPIView.as_view(), name="recipe-list"),
    path('api/batches/', views.BatchListAPIView.as_view(), name="batch-list"),
    path('api/vessels/', views.VesselListAPIView.as_view(), name="vessel-list"),
]