# Generated by Django 4.2.2 on 2023-07-25 17:10

from django.db import migrations
import quantityfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0003_remove_recipefermentable_amount_is_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipefermentable',
            name='amount_actual',
        ),
        migrations.AddField(
            model_name='recipefermentable',
            name='amount_volume',
            field=quantityfield.fields.QuantityField(base_units='liters', blank=True, null=True, unit_choices=['liters']),
        ),
        migrations.AddField(
            model_name='recipefermentable',
            name='amount_weight',
            field=quantityfield.fields.QuantityField(base_units='kilograms', blank=True, null=True, unit_choices=['kilograms']),
        ),
    ]
