# Generated by Django 4.2.2 on 2023-08-03 02:48

from django.db import migrations
import quantityfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0007_remove_recipefermentable_amount_metric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='estFG',
            field=quantityfield.fields.QuantityField(base_units='sg', unit_choices=['sg']),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='estOG',
            field=quantityfield.fields.QuantityField(base_units='sg', unit_choices=['sg']),
        ),
    ]
