# Generated by Django 4.2.2 on 2023-08-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0010_remove_recipe_adjuncts_remove_recipe_fermentables_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeadjunct',
            name='recipe',
            field=models.ManyToManyField(related_name='adjuncts', to='batchthis.recipe'),
        ),
        migrations.AddField(
            model_name='recipefermentable',
            name='recipe',
            field=models.ManyToManyField(related_name='fermentables', to='batchthis.recipe'),
        ),
        migrations.AddField(
            model_name='recipeyeasts',
            name='recipe',
            field=models.ManyToManyField(related_name='yeasts', to='batchthis.recipe'),
        ),
    ]
