# Generated by Django 4.2.2 on 2023-08-20 12:33

import apps.batchthis.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0011_recipeadjunct_recipe_recipefermentable_recipe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipefermentable',
            old_name='notes',
            new_name='recipe_notes',
        ),
        migrations.RemoveField(
            model_name='recipeadjunct',
            name='amount_is_weight',
        ),
        migrations.RemoveField(
            model_name='recipeadjunct',
            name='amount_metric',
        ),
        migrations.AddField(
            model_name='recipeadjunct',
            name='amount_volume',
            field=apps.batchthis.models.PrecisionQuantityField(base_units='liters', blank=True, null=True, precision='.2f', unit_choices=['liters']),
        ),
        migrations.AddField(
            model_name='recipeadjunct',
            name='amount_weight',
            field=apps.batchthis.models.PrecisionQuantityField(base_units='kilograms', blank=True, null=True, precision='.2f', unit_choices=['kilograms']),
        ),
        migrations.AlterField(
            model_name='recipeadjunct',
            name='time_to_add',
            field=apps.batchthis.models.PrecisionQuantityField(base_units='min', precision='.2f', unit_choices=['min']),
        ),
        migrations.AlterField(
            model_name='recipefermentable',
            name='amount_volume',
            field=apps.batchthis.models.PrecisionQuantityField(base_units='liters', blank=True, null=True, precision='.2f', unit_choices=['liters']),
        ),
        migrations.AlterField(
            model_name='recipefermentable',
            name='amount_weight',
            field=apps.batchthis.models.PrecisionQuantityField(base_units='kilograms', blank=True, null=True, precision='.2f', unit_choices=['kilograms']),
        ),
    ]
