# Generated by Django 4.2.2 on 2023-08-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0014_recipeadjunct_intended_use'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeyeasts',
            name='recipe_notes',
        ),
        migrations.AlterField(
            model_name='recipeadjunct',
            name='recipe_notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
