# Generated by Django 4.2.2 on 2023-08-26 18:44

import apps.batchthis.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0015_remove_recipeyeasts_recipe_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeadjunct',
            name='amount_volume',
            field=apps.batchthis.fields.DescriptiveQuantityField(base_units='liters', blank=True, null=True, unit_choices=['liters']),
        ),
        migrations.AlterField(
            model_name='recipeadjunct',
            name='amount_weight',
            field=apps.batchthis.fields.DescriptiveQuantityField(base_units='kilograms', blank=True, null=True, unit_choices=['kilograms']),
        ),
        migrations.AlterField(
            model_name='recipefermentable',
            name='amount_volume',
            field=apps.batchthis.fields.DescriptiveQuantityField(base_units='liters', blank=True, null=True, unit_choices=['liters']),
        ),
        migrations.AlterField(
            model_name='recipefermentable',
            name='amount_weight',
            field=apps.batchthis.fields.DescriptiveQuantityField(base_units='kilograms', blank=True, null=True, unit_choices=['kilograms']),
        ),
    ]
