# Generated by Django 4.2.2 on 2023-09-09 17:52

import apps.batchthis.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0016_alter_recipeadjunct_amount_volume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='batchSize',
            field=apps.batchthis.fields.DescriptiveQuantityField(base_units='liters', unit_choices=['liters']),
        ),
    ]
