# Generated by Django 5.1.5 on 2025-02-10 19:58

import apps.batchthis.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0017_alter_recipe_batchsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='estFG',
            field=apps.batchthis.fields.DescriptiveQuantityField(base_units='sg', unit_choices=['sg']),
        ),
    ]
