# Generated by Django 5.1.5 on 2025-02-15 00:57

import apps.batchthis.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0019_rename_amount_volume_recipeadjunct__amount_volume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeyeasts',
            name='amount_is_weight',
        ),
        migrations.AddField(
            model_name='recipeyeasts',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recipeadjunct',
            name='time_to_add',
            field=apps.batchthis.fields.DescriptiveQuantityField(base_units='min', unit_choices=['min']),
        ),
        migrations.AlterField(
            model_name='recipeyeasts',
            name='amount',
            field=apps.batchthis.fields.DescriptiveQuantityField(base_units='kilograms', unit_choices=['kilograms']),
        ),
    ]
