# Generated by Django 5.1.5 on 2025-02-15 01:02

import apps.batchthis.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0020_remove_recipeyeasts_amount_is_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yeast',
            name='max_temp',
            field=apps.batchthis.fields.DescriptiveQuantityField(base_units='celsius', unit_choices=['celsius']),
        ),
        migrations.AlterField(
            model_name='yeast',
            name='min_temp',
            field=apps.batchthis.fields.DescriptiveQuantityField(base_units='celsius', unit_choices=['celsius']),
        ),
    ]
