# Generated by Django 5.1.5 on 2025-02-16 15:22

import apps.batchthis.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0023_alter_adjunct_notes_alter_adjunct_ratio_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeadjunct',
            name='test_amount',
            field=apps.batchthis.fields.DescriptiveQuantityField(base_units='kilogram', blank=True, null=True, unit_choices=['kilogram']),
        ),
        migrations.AddField(
            model_name='recipefermentable',
            name='test_amount',
            field=apps.batchthis.fields.DescriptiveQuantityField(base_units='kilogram', blank=True, null=True, unit_choices=['kilogram']),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='batchSize',
            field=apps.batchthis.fields.DescriptiveQuantityField(base_units='liters', unit_choices=['liters', 'gallons']),
        ),
        migrations.AlterField(
            model_name='recipeadjunct',
            name='_amount_volume',
            field=apps.batchthis.fields.DescriptiveQuantityField(base_units='liters', blank=True, null=True, unit_choices=['liters', 'floz', 'ml', 'gallon', 'liter']),
        ),
        migrations.AlterField(
            model_name='recipeadjunct',
            name='_amount_weight',
            field=apps.batchthis.fields.DescriptiveQuantityField(base_units='kilograms', blank=True, null=True, unit_choices=['kilograms', 'lb', 'gram', 'oz', 'milligram', 'kilogram']),
        ),
        migrations.AlterField(
            model_name='recipefermentable',
            name='_amount_volume',
            field=apps.batchthis.fields.DescriptiveQuantityField(base_units='liters', blank=True, null=True, unit_choices=['liters', 'floz', 'ml', 'gallon', 'liter']),
        ),
        migrations.AlterField(
            model_name='recipefermentable',
            name='_amount_weight',
            field=apps.batchthis.fields.DescriptiveQuantityField(base_units='kilograms', blank=True, null=True, unit_choices=['kilograms', 'lb', 'gram', 'oz', 'milligram', 'kilogram']),
        ),
        migrations.AlterField(
            model_name='yeast',
            name='max_temp',
            field=apps.batchthis.fields.DescriptiveQuantityField(base_units='degC', unit_choices=['degC', 'degF']),
        ),
        migrations.AlterField(
            model_name='yeast',
            name='min_temp',
            field=apps.batchthis.fields.DescriptiveQuantityField(base_units='degC', unit_choices=['degC', 'degF']),
        ),
    ]
