# Generated by Django 5.1.5 on 2025-02-17 03:40

import apps.batchthis.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0025_rename_test_amount_recipeadjunct_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='size_units',
        ),
        migrations.AlterField(
            model_name='batch',
            name='size',
            field=apps.batchthis.fields.DescriptiveQuantityField(base_units='liters', unit_choices=['liters', 'gallons']),
        ),
    ]
