# Generated by Django 5.1.5 on 2025-02-19 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0026_remove_batch_size_units_alter_batch_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='batchthis.batchcategory'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='batchthis.recipe'),
        ),
        migrations.AlterField(
            model_name='recipeadjunct',
            name='adjunct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='batchthis.adjunct'),
        ),
        migrations.AlterField(
            model_name='recipeyeasts',
            name='yeast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='batchthis.yeast'),
        ),
    ]
