# Generated by Django 6.1 on 2026-09-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0028_remove_batch_fermenter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='startdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
