# Generated by Django 6.1 on 2026-09-22 16:39
#
# Trimmed by hand before this migration was ever applied: makemigrations also
# picked up an unrelated, pre-existing Yeast.form drift (a model change made
# at some earlier point without a matching migration) alongside the intended
# Vessel/VesselStatusEvent changes. That's a separate, deliberate fix for
# someone to make on its own - not bundled in here.

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0029_alter_batch_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='status',
            field=models.CharField(choices=[('Clean/Ready', 'Clean/Ready'), ('In Use', 'In Use'), ('Needs Cleaning', 'Needs Cleaning')], default='Clean/Ready', max_length=15),
        ),
        migrations.CreateModel(
            name='VesselStatusEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Clean/Ready', 'Clean/Ready'), ('In Use', 'In Use'), ('Needs Cleaning', 'Needs Cleaning')], max_length=15)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='batchthis.batch')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='batchthis.vessel')),
            ],
            options={
                'verbose_name': 'vessel status event',
                'ordering': ['timestamp'],
            },
        ),
    ]
