# Generated by Django 6.1 on 2026-09-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0030_vessel_status_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yeast',
            name='form',
            field=models.CharField(choices=[('dry', 'Dry'), ('liquid', 'Liquid')], max_length=20, verbose_name='Format'),
        ),
    ]
