# Generated by Django 6.1 on 2026-09-23 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0031_yeast_form_verbose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='batches', to='batchthis.vessel'),
        ),
        migrations.AddField(
            model_name='vesselstatusevent',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('Clean/Ready', 'Clean/Ready'), ('In Use', 'In Use'), ('Needs Cleaning', 'Needs Cleaning'), ('Out of Service', 'Out of Service')], max_length=15),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='status',
            field=models.CharField(choices=[('Clean/Ready', 'Clean/Ready'), ('In Use', 'In Use'), ('Needs Cleaning', 'Needs Cleaning'), ('Out of Service', 'Out of Service')], default='Clean/Ready', max_length=15),
        ),
        migrations.AlterField(
            model_name='vesselstatusevent',
            name='status',
            field=models.CharField(choices=[('Clean/Ready', 'Clean/Ready'), ('In Use', 'In Use'), ('Needs Cleaning', 'Needs Cleaning'), ('Out of Service', 'Out of Service')], max_length=15),
        ),
    ]
