# Generated by Django 6.1 on 2026-09-23 13:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0032_batch_vessel_vesselstatusevent_previous_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='startdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
