# Generated by Django 6.1 on 2026-09-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0033_alter_batch_startdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchstage',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='batchstage',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='batchstage',
            name='from_state',
            field=models.CharField(blank=True, choices=[('', 'Start'), ('Fermentation', 'Fermentation'), ('Aging', 'Aging'), ('Bottling', 'Bottling'), ('Completed', 'Completed')], max_length=15),
        ),
        migrations.AddField(
            model_name='batchstage',
            name='shortid',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batchstage',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batchstage',
            name='to_state',
            field=models.CharField(choices=[('Fermentation', 'Fermentation'), ('Aging', 'Aging'), ('Bottling', 'Bottling'), ('Completed', 'Completed')], default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batchstage',
            name='transfers_batch',
            field=models.BooleanField(default=False),
        ),
    ]
