# Generated by Django 6.1 on 2026-09-23 13:46
#
# Second default-data load (after 0002_default_load): seeds the fixed v1 batch
# workflow transitions - see TODO-BatchStage.txt, "CANONICAL WORKFLOW GRAPH".
# Created with `makemigrations --empty`; the RunPython seed below is the one
# hand-written part, as a one-time exception approved by Aaron (2026-09-23).

from django.db import migrations

# (sort_order, shortid, name, from_state, to_state, transfers_batch, description)
# A blank from_state means Start. Code looks these up by shortid.
BATCH_STAGES = [
    (1, "pitch", "Pitch", "", "Fermentation", False, ""),
    (2, "racking", "Racking", "Fermentation", "Aging", True,
     "Transfer off the lees; repeat as needed during Aging"),
    (3, "coarse-filtering", "Coarse Filtering", "Aging", "Aging", True, "5-10 micron"),
    (4, "fine-filtering", "Fine Filtering", "Aging", "Aging", True, "1-1.5 micron"),
    (5, "sterile-filtering", "Sterile Filtering", "Aging", "Bottling", True, "0.5 micron"),
    (6, "complete-batch", "Complete Batch", "Bottling", "Completed", False,
     "Closes out the batch"),
]


def loadDefaults(apps, schema_editor):
    db = schema_editor.connection.alias
    BatchStage = apps.get_model('batchthis', 'BatchStage')
    for sort_order, shortid, name, from_state, to_state, transfers_batch, description in BATCH_STAGES:
        BatchStage.objects.using(db).update_or_create(
            shortid=shortid,
            defaults={
                'sort_order': sort_order,
                'name': name,
                'from_state': from_state,
                'to_state': to_state,
                'transfers_batch': transfers_batch,
                'description': description,
            },
        )


def removeDefaults(apps, schema_editor):
    db = schema_editor.connection.alias
    BatchStage = apps.get_model('batchthis', 'BatchStage')
    BatchStage.objects.using(db).filter(shortid__in=[row[1] for row in BATCH_STAGES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0034_batchstage_transitions'),
    ]

    operations = [
        migrations.RunPython(loadDefaults, removeDefaults),
    ]
