# Generated by Django 6.1 on 2026-09-23 14:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0035_default_load2'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchStageEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_events', to='batchthis.batch')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='batchthis.batchstage')),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_events', to='batchthis.vessel')),
            ],
            options={
                'ordering': ['timestamp', 'pk'],
            },
        ),
    ]
