# Generated by Django 6.1 on 2026-09-23 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0036_batchstageevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchstageevent',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='batchthis.batchstage'),
        ),
    ]
