# Generated by Django 6.1 on 2026-09-24 00:43

import apps.batchthis.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0037_alter_batchstageevent_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vessel',
            name='max_size',
        ),
        migrations.RemoveField(
            model_name='vessel',
            name='max_size_units',
        ),
        migrations.RemoveField(
            model_name='vessel',
            name='used_size',
        ),
        migrations.RemoveField(
            model_name='vessel',
            name='used_size_units',
        ),
        migrations.AddField(
            model_name='vessel',
            name='capacity',
            field=apps.batchthis.fields.DescriptiveQuantityField(base_units='liters', default='6 gallons', unit_choices=['liters', 'gallons']),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vessel',
            name='fill',
            field=apps.batchthis.fields.DescriptiveQuantityField(base_units='liters', blank=True, null=True, unit_choices=['liters', 'gallons']),
        ),
    ]
