# Generated by Django 6.1 on 2026-09-24 11:08

import apps.batchthis.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0038_vessel_capacity_fill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchaddition',
            name='name',
        ),
        migrations.RemoveField(
            model_name='batchaddition',
            name='units',
        ),
        migrations.AddField(
            model_name='batchaddition',
            name='adjunct',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='batch_additions', to='batchthis.adjunct'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batchaddition',
            name='amount',
            field=apps.batchthis.fields.DescriptiveQuantityField(base_units='kilograms', unit_choices=['kilograms']),
        ),
    ]
