# Generated by Django 6.1 on 2026-09-24 11:51

import apps.batchthis.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0039_batchaddition_adjunct_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchtest',
            name='units',
        ),
        migrations.AlterField(
            model_name='batchtest',
            name='value',
            field=apps.batchthis.fields.DescriptiveQuantityField(base_units='dimensionless', unit_choices=['dimensionless']),
        ),
    ]
