# Generated by Django 6.1 on 2026-09-24 13:37

import apps.batchthis.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0040_batchtest_reading_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipePlanStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('planned_duration', apps.batchthis.fields.DescriptiveQuantityField(base_units='second', blank=True, null=True, unit_choices=['second'])),
                ('vessel_role', models.CharField(blank=True, max_length=50)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_steps', to='batchthis.recipe')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_steps', to='batchthis.batchstage')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='workflow_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='batchthis.workflowtemplate'),
        ),
        migrations.CreateModel(
            name='WorkflowTemplateStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('planned_duration', apps.batchthis.fields.DescriptiveQuantityField(base_units='second', blank=True, null=True, unit_choices=['second'])),
                ('vessel_role', models.CharField(blank=True, max_length=50)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_steps', to='batchthis.batchstage')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='batchthis.workflowtemplate')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
                'abstract': False,
            },
        ),
    ]
