# Generated by Django 6.1 on 2026-09-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0041_workflow_plans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeplanstep',
            name='vessel_role',
        ),
        migrations.RemoveField(
            model_name='workflowtemplatestep',
            name='vessel_role',
        ),
        migrations.AddField(
            model_name='recipeplanstep',
            name='vessel_type',
            field=models.CharField(choices=[('Fermenter', 'Fermenter'), ('Aging Tank', 'Aging Tank'), ('Barrel', 'Barrel'), ('current', 'None / Current')], default='current', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workflowtemplatestep',
            name='vessel_type',
            field=models.CharField(choices=[('Fermenter', 'Fermenter'), ('Aging Tank', 'Aging Tank'), ('Barrel', 'Barrel'), ('current', 'None / Current')], default='current', max_length=15),
            preserve_default=False,
        ),
    ]
