# Generated by Django 6.1 on 2026-09-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0042_plan_step_vessel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeplanstep',
            name='vessel_type',
            field=models.CharField(choices=[('Fermenter', 'Fermenter'), ('Aging Tank', 'Aging Tank'), ('Barrel', 'Barrel'), ('Bottles', 'Bottles'), ('Kegs', 'Kegs'), ('current', 'None / Current')], max_length=15),
        ),
        migrations.AlterField(
            model_name='workflowtemplatestep',
            name='vessel_type',
            field=models.CharField(choices=[('Fermenter', 'Fermenter'), ('Aging Tank', 'Aging Tank'), ('Barrel', 'Barrel'), ('Bottles', 'Bottles'), ('Kegs', 'Kegs'), ('current', 'None / Current')], max_length=15),
        ),
    ]
