# Generated by Django 6.1 on 2026-09-24 19:24

import apps.batchthis.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0043_plan_step_packaging_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='workflow_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='batchthis.workflowtemplate'),
        ),
        migrations.CreateModel(
            name='BatchPlanStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('planned_duration', apps.batchthis.fields.DescriptiveQuantityField(base_units='second', blank=True, null=True, unit_choices=['second'])),
                ('vessel_type', models.CharField(choices=[('Fermenter', 'Fermenter'), ('Aging Tank', 'Aging Tank'), ('Barrel', 'Barrel'), ('Bottles', 'Bottles'), ('Kegs', 'Kegs'), ('current', 'None / Current')], max_length=15)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_steps', to='batchthis.batch')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_steps', to='batchthis.batchstage')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
                'abstract': False,
            },
        ),
    ]
