# Generated by Django 6.1 on 2026-09-24 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0044_batch_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='packaging',
            field=models.CharField(blank=True, choices=[('Bottles', 'Bottles'), ('Kegs', 'Kegs')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='batchstageevent',
            name='packaging',
            field=models.CharField(blank=True, choices=[('Bottles', 'Bottles'), ('Kegs', 'Kegs')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='batchstageevent',
            name='plan_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='batchthis.batchplanstep'),
        ),
    ]
