# Generated by Django 6.1 on 2026-09-25 18:50

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0045_stage_event_plan_links_packaging'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='pairing',
        ),
        migrations.CreateModel(
            name='PairingTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Lower('name')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_pairing_tag_name_ignoring_case')],
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='pairings',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='batchthis.pairingtag'),
        ),
    ]
