# Generated by Django 6.1 on 2026-09-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0046_remove_recipe_pairing_pairingtag_recipe_pairings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjunct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fermentable',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fermentabletype',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recipeadjunct',
            name='recipe_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipefermentable',
            name='recipe_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yeast',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yeast',
            name='flocculation',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='yeast',
            name='form',
            field=models.CharField(blank=True, choices=[('dry', 'Dry'), ('liquid', 'Liquid')], max_length=20, verbose_name='Format'),
        ),
    ]
