# Generated by Django 6.1 on 2026-10-03 18:53

import apps.batchthis.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0047_alter_adjunct_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('fermentable', 'Fermentable'), ('adjunct', 'Adjunct'), ('yeast', 'Yeast')], max_length=12)),
                ('recipe_amount', apps.batchthis.fields.DescriptiveQuantityField(base_units='kilogram', blank=True, null=True, unit_choices=['kilogram'])),
                ('amount', apps.batchthis.fields.DescriptiveQuantityField(base_units='kilogram', blank=True, null=True, unit_choices=['kilogram'])),
                ('time_to_add', apps.batchthis.fields.DescriptiveQuantityField(base_units='min', blank=True, null=True, unit_choices=['min'])),
                ('notes', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('adjunct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='batchthis.adjunct')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='batchthis.batch')),
                ('fermentable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='batchthis.fermentable')),
                ('intended_use', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='batchthis.adjunctusage')),
                ('yeast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='batchthis.yeast')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
