# Generated by Django 6.1 on 2026-10-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0048_batch_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='yeast',
            name='nitrogen_requirement',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='', max_length=6, verbose_name='Nitrogen demand'),
        ),
    ]
