# Generated by Django 4.2.2 on 2023-07-25 01:06

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import quantityfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Adjunct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('supplier', models.CharField(blank=True, max_length=75, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('use_for', models.CharField(max_length=50, null=True)),
                ('notes', models.CharField(max_length=200, null=True)),
                ('ratio_batch_size', models.CharField(max_length=15)),
                ('ratio_amount', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdjunctType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AdjunctUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('startdate', models.DateTimeField(auto_now=True)),
                ('enddate', models.DateTimeField(blank=True, null=True)),
                ('lotId', models.CharField(max_length=7, null=True)),
                ('size', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('startingGravity', models.FloatField()),
                ('estimatedEndGravity', models.FloatField()),
                ('activity', models.ManyToManyField(blank=True, related_name='batch', to='batchthis.activitylog')),
            ],
            options={
                'verbose_name_plural': 'batches',
            },
        ),
        migrations.CreateModel(
            name='BatchAdditionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of this addition item.', max_length=50)),
                ('maker', models.CharField(blank=True, help_text='Name of the company who made this item.', max_length=50)),
                ('lotid', models.CharField(blank=True, help_text='The lot or batch id of this item.  Useful when looking for batches made with bad Lot', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BatchCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('bjcp_code', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name_plural': 'batch categories',
            },
        ),
        migrations.CreateModel(
            name='BatchNoteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BatchStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BatchStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BatchTestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('shortid', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fermentable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('supplier', models.CharField(blank=True, max_length=75, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('sugar_content', models.FloatField()),
                ('potential', models.FloatField()),
                ('color', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FermentableType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text="Enter the unit identifier, i.e. 'mgL' or 'ph'", max_length=10)),
                ('label', models.CharField(help_text="Enter abbreviation label of the measured unit, i.e. 'mg/L'", max_length=25, null=True)),
                ('name', models.CharField(help_text='Descriptive Name of the measuring unit.', max_length=25, null=True)),
                ('category', models.SmallIntegerField(choices=[(0, 'Temperature'), (1, 'Concentration/Density'), (2, 'Weight/Mass'), (3, 'pH'), (4, 'Timing'), (5, 'Volume')])),
            ],
        ),
        migrations.CreateModel(
            name='Yeast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('supplier', models.CharField(blank=True, max_length=75, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(max_length=20)),
                ('form', models.CharField(choices=[('dry', 'Dry'), ('liquid', 'Liquid')], max_length=20)),
                ('min_temp', models.FloatField()),
                ('max_temp', models.FloatField()),
                ('flocculation', models.CharField(max_length=7)),
                ('attenuation', models.FloatField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('max_size', models.IntegerField()),
                ('used_size', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='Clean/Ready', max_length=15)),
                ('intended_use', models.CharField(max_length=30)),
                ('max_size_units', models.ForeignKey(on_delete=models.SET('_del'), related_name='fermenter_max_size_units', to='batchthis.unit')),
                ('used_size_units', models.ForeignKey(blank=True, null=True, on_delete=models.SET('_del'), related_name='fermenter_used_size_units', to='batchthis.unit')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeYeasts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('recipe_notes', models.TextField(blank=True, null=True)),
                ('amount_is_weight', models.BooleanField()),
                ('yeast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batchthis.yeast')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeFermentable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_metric', models.FloatField(default=0)),
                ('amount_actual', quantityfield.fields.QuantityField(base_units='kilogram', unit_choices=['kilogram'])),
                ('amount_is_weight', models.BooleanField()),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('is_fermentable', models.BooleanField(blank=True, null=True)),
                ('fermentable', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='batchthis.fermentable')),
                ('intended_use', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batchthis.adjunctusage')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeAdjunct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_metric', models.FloatField(default=0)),
                ('time_to_add', models.FloatField()),
                ('amount_is_weight', models.BooleanField()),
                ('recipe_notes', models.TextField(blank=True, null=True)),
                ('adjunct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batchthis.adjunct')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bs_file', models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='media/recipes'), upload_to='')),
                ('name', models.CharField(max_length=75)),
                ('dateCreated', models.DateField()),
                ('dateUpdated', models.DateField(blank=True, null=True)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('brewer', models.CharField(max_length=30, null=True)),
                ('batchSize', models.FloatField()),
                ('source', models.CharField(max_length=50, null=True)),
                ('pairing', models.CharField(max_length=250, null=True)),
                ('notes', models.TextField()),
                ('estOG', models.FloatField()),
                ('estFG', models.FloatField()),
                ('estABV', models.FloatField()),
                ('adjuncts', models.ManyToManyField(to='batchthis.recipeadjunct')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batchthis.batchcategory')),
                ('fermentables', models.ManyToManyField(to='batchthis.recipefermentable')),
                ('yeasts', models.ManyToManyField(to='batchthis.recipeyeasts')),
            ],
            options={
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Fermenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_passivation', models.DateField(null=True)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batchthis.vessel')),
            ],
        ),
        migrations.AddField(
            model_name='fermentable',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batchthis.fermentabletype'),
        ),
        migrations.CreateModel(
            name='BatchTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('value', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=250)),
                ('batch', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='batchthis.batch')),
                ('type', models.ForeignKey(on_delete=models.SET('_del'), to='batchthis.batchtesttype')),
                ('units', models.ForeignKey(on_delete=models.SET('_del'), to='batchthis.unit')),
            ],
        ),
        migrations.CreateModel(
            name='BatchNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='batchthis.batch')),
                ('notetype', models.ForeignKey(on_delete=models.SET('_del'), to='batchthis.batchnotetype')),
            ],
        ),
        migrations.AddField(
            model_name='batchcategory',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batchthis.batchstyle'),
        ),
        migrations.CreateModel(
            name='BatchAddition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='Add a brief description of this Addition item and why', max_length=250)),
                ('amount', models.FloatField()),
                ('batch', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='additions', to='batchthis.batch')),
                ('name', models.ForeignKey(on_delete=models.SET('_del'), to='batchthis.batchadditionitem')),
                ('units', models.ForeignKey(on_delete=models.SET('_del'), to='batchthis.unit')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('_del'), to='batchthis.batchcategory'),
        ),
        migrations.AddField(
            model_name='batch',
            name='fermenter',
            field=models.ManyToManyField(blank=True, related_name='batch', to='batchthis.fermenter'),
        ),
        migrations.AddField(
            model_name='batch',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('_del'), to='batchthis.recipe'),
        ),
        migrations.AddField(
            model_name='batch',
            name='size_units',
            field=models.ForeignKey(on_delete=models.SET('_del'), to='batchthis.unit'),
        ),
        migrations.CreateModel(
            name='Barrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=20)),
                ('toastLevel', models.CharField(max_length=25)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batchthis.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='AgingTank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batchthis.vessel')),
            ],
        ),
        migrations.AddField(
            model_name='adjunct',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batchthis.adjuncttype'),
        ),
        migrations.AddField(
            model_name='adjunct',
            name='use',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batchthis.adjunctusage'),
        ),
    ]
