# Generated by Django 4.2.2 on 2023-07-25 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0002_default_load'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipefermentable',
            name='amount_is_weight',
        ),
    ]
