# Generated by Django 4.2.2 on 2023-07-30 15:01

from django.db import migrations
import quantityfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0004_remove_recipefermentable_amount_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='estimatedEndGravity',
            field=quantityfield.fields.QuantityField(base_units='sg', unit_choices=['sg']),
        ),
        migrations.AlterField(
            model_name='batch',
            name='startingGravity',
            field=quantityfield.fields.QuantityField(base_units='sg', unit_choices=['sg']),
        ),
        migrations.AlterField(
            model_name='recipefermentable',
            name='amount_volume',
            field=quantityfield.fields.QuantityField(base_units='liters', blank=True, null=True, unit_choices=['liters', 'floz', 'ml', 'gallon', 'liter']),
        ),
        migrations.AlterField(
            model_name='recipefermentable',
            name='amount_weight',
            field=quantityfield.fields.QuantityField(base_units='kilograms', blank=True, null=True, unit_choices=['kilograms', 'lb', 'gram', 'oz', 'milligram', 'kilogram']),
        ),
    ]
