# Generated by Django 4.2.2 on 2023-08-01 01:17

from django.db import migrations
import quantityfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0005_alter_batch_estimatedendgravity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='batchSize',
            field=quantityfield.fields.QuantityField(base_units='liters', unit_choices=['liters', 'gallons']),
        ),
    ]
