# Generated by Django 4.2.2 on 2023-08-02 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0006_alter_recipe_batchsize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipefermentable',
            name='amount_metric',
        ),
    ]
