# Generated by Django 4.2.2 on 2023-08-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0008_alter_recipe_estfg_alter_recipe_estog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='adjuncts',
            field=models.ManyToManyField(related_name='adjuncts', to='batchthis.recipeadjunct'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fermentables',
            field=models.ManyToManyField(related_name='fermentables', to='batchthis.recipefermentable'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='yeasts',
            field=models.ManyToManyField(related_name='yeasts', to='batchthis.recipeyeasts'),
        ),
    ]
