# Generated by Django 4.2.2 on 2023-08-06 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0009_alter_recipe_adjuncts_alter_recipe_fermentables_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='adjuncts',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='fermentables',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='yeasts',
        ),
    ]
