# Generated by Django 4.2.2 on 2023-08-20 13:05

import batchthis.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0012_rename_notes_recipefermentable_recipe_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='estFG',
            field=batchthis.models.PrecisionQuantityField(base_units='sg', precision='.2f', unit_choices=['sg']),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='estOG',
            field=batchthis.models.PrecisionQuantityField(base_units='sg', precision='.2f', unit_choices=['sg']),
        ),
    ]
