# Generated by Django 4.2.2 on 2023-08-20 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0013_alter_recipe_estfg_alter_recipe_estog'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeadjunct',
            name='intended_use',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='batchthis.adjunctusage'),
            preserve_default=False,
        ),
    ]
