# Generated by Django 5.1.5 on 2025-02-14 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0018_alter_recipe_estfg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeadjunct',
            old_name='amount_volume',
            new_name='_amount_volume',
        ),
        migrations.RenameField(
            model_name='recipeadjunct',
            old_name='amount_weight',
            new_name='_amount_weight',
        ),
        migrations.RenameField(
            model_name='recipefermentable',
            old_name='amount_volume',
            new_name='_amount_volume',
        ),
        migrations.RenameField(
            model_name='recipefermentable',
            old_name='amount_weight',
            new_name='_amount_weight',
        ),
    ]
