# Generated by Django 5.1.5 on 2025-02-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0021_alter_yeast_max_temp_alter_yeast_min_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='yeast',
            name='alc_tolerance',
            field=models.IntegerField(default=0, verbose_name='Alcohol Tolerance %'),
        ),
    ]
