# Generated by Django 5.1.5 on 2025-02-15 01:41

import batchthis.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0022_yeast_alc_tolerance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjunct',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adjunct',
            name='ratio_amount',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='adjunct',
            name='ratio_batch_size',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='adjunct',
            name='use_for',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='yeast',
            name='max_temp',
            field=batchthis.fields.DescriptiveQuantityField(base_units='degC', unit_choices=['degC']),
        ),
        migrations.AlterField(
            model_name='yeast',
            name='min_temp',
            field=batchthis.fields.DescriptiveQuantityField(base_units='degC', unit_choices=['degC']),
        ),
    ]
