# Generated by Django 5.1.5 on 2025-02-16 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0024_recipeadjunct_test_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeadjunct',
            old_name='test_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='recipefermentable',
            old_name='test_amount',
            new_name='amount',
        ),
    ]
