# Generated by Django 5.1.5 on 2025-02-20 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchthis', '0027_alter_batch_category_alter_batch_recipe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='fermenter',
        ),
        migrations.AlterField(
            model_name='recipeadjunct',
            name='intended_use',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='batchthis.adjunctusage'),
        ),
        migrations.AlterField(
            model_name='recipefermentable',
            name='intended_use',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='batchthis.adjunctusage'),
        ),
        migrations.AddField(
            model_name='batch',
            name='fermenter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='batchthis.fermenter'),
            preserve_default=False,
        ),
    ]
